plugins {
    id 'java'
    id 'application'
    id 'com.github.johnrengelman.shadow' version '8.1.1'
}

group = 'dev.xdpxi'
version = '1.0.3'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'

	implementation("com.formdev:flatlaf:3.7")
}

application {
    mainClass = 'Main'
}

shadowJar {
    archiveClassifier.set("")
    configurations = [project.configurations.runtimeClasspath]

    manifest {
        attributes(
                'Main-Class': 'dev.xdpxi.pixelleap.Main'
        )
    }
}

jar {
    enabled = false
}

test {
    useJUnitPlatform()
}
